name: gcn_modern
channels:
  - dglteam
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.16=py310haa95532_0
  - arrow=1.3.0=py310haa95532_0
  - astroid=2.14.2=py310haa95532_0
  - asttokens=3.0.0=py310haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=24.3.0=py310haa95532_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - aws-c-auth=0.8.0=h2219d47_15
  - aws-c-cal=0.8.1=h099ea23_3
  - aws-c-common=0.10.6=h2466b09_0
  - aws-c-compression=0.3.0=h099ea23_5
  - aws-c-event-stream=0.5.0=h85d8506_11
  - aws-c-http=0.9.2=h3888f84_4
  - aws-c-io=0.15.3=hc5a9e45_6
  - aws-c-mqtt=0.11.0=h2c94728_12
  - aws-c-s3=0.7.7=h6a38c86_0
  - aws-c-sdkutils=0.2.1=h099ea23_4
  - aws-checksums=0.2.2=h099ea23_4
  - aws-crt-cpp=0.29.7=h0642867_7
  - aws-sdk-cpp=1.11.458=h5f5f9c4_4
  - babel=2.16.0=py310haa95532_0
  - backports.tarfile=1.2.0=py310haa95532_0
  - bcrypt=4.3.0=py310h636fa0f_0
  - beautifulsoup4=4.13.5=py310haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=25.1.0=py310haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py310haa95532_0
  - bottleneck=1.4.2=py310hc99e966_0
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - certifi=2025.10.5=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_0
  - chardet=5.2.0=py310haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py310haa95532_0
  - cloudpickle=3.1.1=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - contourpy=1.3.1=py310h214f63a_0
  - cookiecutter=2.6.0=py310haa95532_1
  - cpuonly=2.0=0
  - cryptography=46.0.2=py310h114bc41_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.16=py310h885b0b7_0
  - decorator=5.2.1=py310haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dgl=2.0.0=py310_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.4.0=py310haa95532_0
  - docstring-to-markdown=0.17=py310haa95532_0
  - docutils=0.21.2=py310haa95532_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py310haa95532_0
  - flake8=6.0.0=py310haa95532_0
  - fonttools=4.60.1=py310h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - glib=2.84.2=h232b036_0
  - glib-tools=2.84.2=h08ed4da_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.7=py310haa95532_0
  - imagesize=1.4.1=py310haa95532_0
  - importlib-metadata=8.5.0=py310haa95532_0
  - inflection=0.5.1=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.30.1=py310haa95532_0
  - ipython=8.30.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.13.2=py310haa95532_1
  - jaraco.classes=3.4.0=py310haa95532_0
  - jaraco.context=6.0.0=py310haa95532_0
  - jaraco.functools=4.1.0=py310haa95532_0
  - jedi=0.18.1=py310haa95532_1
  - jellyfish=1.1.3=py310h8ecf97c_0
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.2=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py310haa95532_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - jupyterlab_pygments=0.3.0=py310haa95532_0
  - keyring=25.6.0=py310haa95532_0
  - kiwisolver=1.4.8=py310h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lazy-object-proxy=1.10.0=py310h827c3e9_1
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libarrow=18.1.0=h7377be5_4_cuda
  - libarrow-acero=18.1.0=hf0642a6_4_cuda
  - libarrow-dataset=18.1.0=hf0642a6_4_cuda
  - libarrow-substrait=18.1.0=h322cffe_4_cuda
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h3671451_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libgoogle-cloud=2.31.0=h07d40e7_0
  - libgoogle-cloud-storage=2.31.0=he5eb982_0
  - libgrpc=1.67.1=h7aa3b8a_0
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libparquet=18.1.0=hbdea95a_4_cuda
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.20=h70ee33d_0
  - libprotobuf=5.28.2=hcaed137_0
  - libre2-11=2024.07.02=h4eb7d71_2
  - libsodium=1.0.20=h83e8143_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.5.1=hd77b12b_0
  - libutf8proc=2.9.0=h2466b09_1
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.10.4=h0ad7f3c_2
  - libxslt=1.1.37=h2bbff1b_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=py310haa95532_0
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib=3.10.6=py310haa95532_0
  - matplotlib-base=3.10.6=py310h43afe63_0
  - matplotlib-inline=0.1.7=py310haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.2=py310haa95532_0
  - mistune=3.1.2=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - more-itertools=10.3.0=py310haa95532_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - mypy_extensions=1.0.0=py310haa95532_0
  - nbclient=0.10.2=py310haa95532_0
  - nbconvert=7.16.6=py310haa95532_0
  - nbconvert-core=7.16.6=py310haa95532_0
  - nbconvert-pandoc=7.16.6=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numexpr=2.11.0=py310hdb065b2_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - numpydoc=1.9.0=py310haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.4=h725018a_0
  - orc=2.0.3=h34659fe_0
  - packaging=25.0=py310haa95532_0
  - pandas=2.1.4=py310h4ed8f06_0
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py310haa95532_0
  - paramiko=3.5.0=py310haa95532_0
  - parso=0.8.4=py310haa95532_0
  - pathspec=0.12.1=py310haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pexpect=4.9.0=py310haa95532_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.3.7=py310haa95532_0
  - pluggy=1.5.0=py310haa95532_0
  - ply=3.11=py310haa95532_0
  - prompt-toolkit=3.0.52=py310haa95532_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - psutil=7.0.0=py310h02ab6af_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py310haa95532_0
  - pyarrow=18.1.0=py310h5588dad_0
  - pyarrow-core=18.1.0=py310h8b91b4e_0_cuda
  - pycodestyle=2.10.0=py310haa95532_0
  - pycparser=2.23=py310haa95532_0
  - pydocstyle=6.3.0=py310haa95532_0
  - pyflakes=3.0.1=py310haa95532_0
  - pygments=2.19.1=py310haa95532_0
  - pylint=2.16.2=py310haa95532_0
  - pylint-venv=3.0.3=py310haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.6.0=py310h581ae37_0
  - pyparsing=3.2.0=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyqtwebengine=5.15.7=py310hd77b12b_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-fastjsonschema=2.20.0=py310haa95532_0
  - python-lsp-black=2.0.0=py310haa95532_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py310haa95532_0
  - python-slugify=8.0.4=py310haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytoolconfig=1.2.6=py310haa95532_0
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=py310haa95532_0
  - pywin32=311=py310h885b0b7_0
  - pywin32-ctypes=0.2.2=py310haa95532_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=27.1.0=py310h7149c55_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qt-main=5.15.2=h879a1e9_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.4.0=py310haa95532_0
  - qtconsole=5.4.2=py310haa95532_0
  - qtpy=2.4.3=py310haa95532_0
  - qtwebkit=5.212=h2bbfb41_5
  - re2=2024.07.02=haf4117d_2
  - referencing=0.30.2=py310haa95532_0
  - requests=2.32.5=py310haa95532_0
  - rich=14.2.0=py310haa95532_0
  - rope=1.13.0=py310haa95532_0
  - rpds-py=0.22.3=py310h636fa0f_0
  - rtree=1.4.1=py310h1e5ca3c_0
  - scikit-learn=1.7.1=py310h3fbe716_0
  - scipy=1.15.3=py310h180bac5_0
  - setuptools=80.9.0=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.17.0=py310haa95532_0
  - snappy=1.2.2=h7fa0ca8_0
  - snowballstemmer=3.0.1=py310haa95532_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py310haa95532_0
  - sphinx=7.3.7=py310h827c3e9_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=5.4.3=py310haa95532_1
  - spyder-kernels=2.4.4=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py310haa95532_0
  - sympy=1.14.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=py310hbc747e5_1
  - threadpoolctl=3.5.0=py310h9909e9c_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.4.0=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.2.1=py310haa95532_0
  - tomlkit=0.13.2=py310haa95532_0
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=py310_cpu
  - tornado=6.5.1=py310h827c3e9_0
  - tqdm=4.67.1=py310h9909e9c_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.10.0=py310h5da7b33_1
  - urllib3=2.5.0=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py310haa95532_0
  - wcwidth=0.2.13=py310haa95532_0
  - webencodings=0.5.1=py310haa95532_1
  - whatthepatch=1.0.7=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wrapt=1.17.0=py310h827c3e9_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.5=h6c54ac7_1
  - zipp=3.21.0=py310haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - future==1.0.0
      - hyperopt==0.2.7
      - py4j==0.10.9.9
      - qstylizer==0.2.2
prefix: C:\Users\Megaport\anaconda3\envs\gcn_modern
