name: node_embedding_p
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39h5769e4c_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=0.7.16=pyhd8ed1ab_0
  - anyio=4.10.0=pyhe01879c_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py39h0802e32_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - astroid=3.3.11=py39hcbf5309_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - asyncssh=2.21.0=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - bcrypt=4.3.0=py39h95bb58a_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=25.1.0=pyha5154f8_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.0.9=py39h99910a6_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39ha55e580_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.1.8=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.0=py39h2b77a98_2
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.9.23=py39hd8ed1ab_0
  - cryptography=45.0.6=py39hddbeac1_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py39h1f3cc84_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.0=pyhd8ed1ab_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - fonttools=4.59.1=py39h5769e4c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py39h6d15d50_0
  - fzf=0.66.0=hb13f615_0
  - glib=2.84.2=h232b036_0
  - glib-tools=2.84.2=h08ed4da_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.18.1=pyh7428d3b_3
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=6.0.1=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.1.3=py39h92a245a_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py39hcbf5309_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyring=25.6.0=pyh7428d3b_0
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.3=default_ha2db4b5_0
  - libdeflate=1.22=h2466b09_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.84.2=h405b238_0
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.50=h7351971_1
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.1.0=h518811d_0
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.0=hfc51747_1
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.3=hfa2b4ca_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39hf73967f_1
  - matplotlib=3.8.4=py39hcbf5309_2
  - matplotlib-base=3.8.4=py39he1095e7_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2024.2.2=h57928b3_16
  - more-itertools=10.7.0=pyhd8ed1ab_0
  - multidict=6.6.3=py39h5769e4c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpydoc=1.9.0=pyhe01879c_1
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.4=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandoc=3.8.2.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=h17e33f8_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - propcache=0.3.1=py39hf73967f_0
  - psutil=7.0.0=py39ha55e580_0
  - pthread-stubs=0.4=h0e40799_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=3.3.8=pyhe01879c_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py39h63afc94_4
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.11=py39he15501f_1
  - pyqt5-sip=12.17.0=py39ha51f57c_1
  - pyqtwebengine=5.15.11=py39h5f1a536_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.9.24=h716150d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gssapi=1.9.0=py39h58d4841_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.12.2=pyhff2d567_0
  - python-lsp-server-base=1.12.2=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pywin32=311=py39h5fb4b08_0
  - pywin32-ctypes=0.2.3=py39hcbf5309_1
  - pywinpty=2.0.15=py39ha51f57c_0
  - pyyaml=6.0.2=py39hf73967f_2
  - pyzmq=27.0.2=py39h248659b_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=h9151539_4
  - qt-webengine=5.15.15=h087ee03_1
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.6.1=pyhd8ed1ab_2
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.3=pyhd8ed1ab_1
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.1.0=pyhe01879c_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.27.0=py39hcab59ba_0
  - rtree=1.4.1=pyh11ca60a_0
  - scikit-learn=1.3.2=py39h7c199eb_2
  - scipy=1.13.1=py39h1a10956_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=py39haa95532_0
  - sip=6.10.0=py39ha51f57c_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sphinx=7.4.7=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.0.7=hd8ed1ab_2
  - spyder-base=6.0.7=py39hcbf5309_2
  - spyder-kernels=3.0.5=win_pyh7428d3b_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py39h9e4d2f2_0
  - superqt=0.7.6=pyhb6d5dde_0
  - tbb=2021.13.0=h18a62a1_3
  - terminado=0.18.1=pyh5737063_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py39h0802e32_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.10.0=py39ha51f57c_1
  - unicodedata2=16.0.0=py39ha55e580_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py39hcbf5309_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=py39haa95532_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py39h0802e32_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.20.1=py39hf73967f_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.23.0=py39h0802e32_3
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - decorator==4.4.2
      - future==1.0.0
      - gensim==4.3.2
      - hyperopt==0.2.7
      - karateclub==1.3.3
      - levenshtein==0.27.1
      - networkx==2.6.3
      - node2vec==0.4.6
      - numpy==1.22.4
      - pandas==1.3.5
      - py4j==0.10.9.9
      - pygsp==0.6.1
      - python-levenshtein==0.27.1
      - python-louvain==0.16
      - rapidfuzz==3.13.0
      - smart-open==7.4.1
prefix: C:\Users\Megaport\anaconda3\envs\node_embedding_p
