name: feature_generation
channels:
  - defaults
dependencies:
  - aiodns=3.5.0=py39haa95532_0
  - aiohappyeyeballs=2.6.1=py39haa95532_0
  - aiohttp=3.12.15=py39h02ab6af_0
  - aiosignal=1.4.0=py39haa95532_0
  - alabaster=0.7.16=py39haa95532_0
  - arrow=1.4.0=py39haa95532_0
  - arrow-cpp=21.0.0=h0399227_0
  - astroid=3.3.11=py39haa95532_0
  - asttokens=3.0.0=py39haa95532_0
  - async-timeout=5.0.1=py39haa95532_0
  - asyncssh=2.17.0=py39haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=25.4.0=py39haa95532_1
  - autopep8=2.0.4=pyhd3eb1b0_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - babel=2.16.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - backports.tarfile=1.2.0=py39haa95532_0
  - bcrypt=4.3.0=py39h636fa0f_0
  - beautifulsoup4=4.13.5=py39haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=25.9.0=py39haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py39haa95532_0
  - bottleneck=1.4.2=py39hc99e966_0
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.9.9=haa95532_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - chardet=5.2.0=py39haa95532_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - click=8.1.8=py39haa95532_0
  - cloudpickle=3.1.1=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - cookiecutter=2.6.0=py39haa95532_1
  - cryptography=46.0.2=py39h114bc41_0
  - debugpy=1.8.16=py39h885b0b7_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.18=py39haa95532_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.4.0=py39haa95532_0
  - docstring-to-markdown=0.17=py39haa95532_0
  - docutils=0.21.2=py39haa95532_1
  - exceptiongroup=1.3.0=py39haa95532_0
  - executing=2.2.1=py39haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - flake8=7.1.1=py39haa95532_0
  - frozenlist=1.8.0=py39h885b0b7_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py39haa95532_0
  - imagesize=1.4.1=py39haa95532_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - inflection=0.5.1=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.30.1=py39haa95532_0
  - ipython=8.15.0=py39haa95532_0
  - isort=6.1.0=py39haa95532_0
  - jaraco.classes=3.4.0=py39haa95532_0
  - jaraco.context=6.0.0=py39haa95532_0
  - jaraco.functools=4.1.0=py39haa95532_0
  - jedi=0.19.2=py39haa95532_0
  - jellyfish=1.1.3=py39h8ecf97c_0
  - jinja2=3.1.6=py39haa95532_0
  - joblib=1.5.2=py39haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py39haa95532_0
  - jsonschema-specifications=2023.7.1=py39haa95532_0
  - jupyter_client=8.6.3=py39haa95532_0
  - jupyter_core=5.8.1=py39haa95532_0
  - jupyterlab_pygments=0.3.0=py39haa95532_0
  - keyring=25.6.0=py39haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libcurl=8.16.0=h97e0424_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=h83e8143_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libuv=1.48.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=2.2.0=py39haa95532_1
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib-inline=0.1.7=py39haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.2=py39haa95532_0
  - mistune=3.1.2=py39haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - more-itertools=10.8.0=py39haa95532_0
  - multidict=6.7.0=py39h02ab6af_0
  - mypy_extensions=1.0.0=py39haa95532_0
  - nbclient=0.10.2=py39haa95532_0
  - nbconvert=7.16.6=py39haa95532_0
  - nbconvert-core=7.16.6=py39haa95532_0
  - nbconvert-pandoc=7.16.6=py39haa95532_0
  - nbformat=5.10.4=py39haa95532_0
  - nest-asyncio=1.6.0=py39haa95532_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - numpydoc=1.9.0=py39haa95532_0
  - openssl=3.0.18=h543e019_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py39haa95532_1
  - pandas=2.3.3=py39ha5e6156_0
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py39haa95532_0
  - parso=0.8.4=py39haa95532_0
  - pathspec=0.12.1=py39haa95532_1
  - pexpect=4.9.0=py39haa95532_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.2=pyhc872135_1
  - platformdirs=4.3.7=py39haa95532_0
  - pluggy=1.5.0=py39haa95532_0
  - ply=3.11=py39haa95532_0
  - prompt-toolkit=3.0.52=py39haa95532_1
  - propcache=0.3.1=py39h827c3e9_0
  - psutil=7.0.0=py39h02ab6af_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py39haa95532_0
  - pyarrow=21.0.0=py39ha5e6156_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycares=4.10.0=py39he29e43d_0
  - pycodestyle=2.12.1=py39haa95532_0
  - pycparser=2.23=py39haa95532_0
  - pydocstyle=6.3.0=py39haa95532_0
  - pyflakes=3.2.0=py39haa95532_0
  - pygithub=2.4.0=py39haa95532_0
  - pygments=2.19.1=py39haa95532_0
  - pyjwt=2.10.1=py39haa95532_0
  - pylint=3.3.8=py39haa95532_0
  - pylint-venv=3.0.3=py39haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.6.0=py39h581ae37_0
  - pyqt=5.15.10=py39h5da7b33_1
  - pyqt5-sip=12.13.0=py39h827c3e9_1
  - pyqtwebengine=5.15.10=py39h5da7b33_1
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.24=h716150d_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-fastjsonschema=2.20.0=py39haa95532_0
  - python-louvain=0.16=py39haa95532_0
  - python-lsp-black=2.0.0=py39haa95532_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.12.2=py39hbc747e5_0
  - python-slugify=8.0.4=py39haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytokens=0.2.0=py39haa95532_0
  - pytoolconfig=1.2.6=py39haa95532_0
  - pytz=2025.2=py39haa95532_0
  - pyuca=1.2=py39haa95532_1
  - pywin32=311=py39h885b0b7_0
  - pywin32-ctypes=0.2.2=py39haa95532_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - pyzmq=27.1.0=py39h7149c55_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py39haa95532_0
  - qt-main=5.15.2=h19c9488_12
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.4.0=py39haa95532_0
  - qtconsole=5.6.1=py39haa95532_1
  - qtpy=2.4.3=py39haa95532_0
  - re2=2024.07.02=h214f63a_0
  - referencing=0.30.2=py39haa95532_0
  - requests=2.32.5=py39haa95532_0
  - rich=14.2.0=py39haa95532_0
  - rope=1.13.0=py39haa95532_0
  - rpds-py=0.22.3=py39h636fa0f_0
  - rtree=1.4.1=py39h1e5ca3c_0
  - scikit-learn=1.5.1=py39hc64d2fc_0
  - setuptools=80.9.0=py39haa95532_0
  - sip=6.7.12=py39h5da7b33_1
  - six=1.17.0=py39haa95532_0
  - smart_open=7.3.1=py39haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - snowballstemmer=3.0.1=py39haa95532_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py39haa95532_0
  - sphinx=7.3.7=py39h827c3e9_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=6.0.7=py39haa95532_1
  - spyder-kernels=3.0.5=py39hbc747e5_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py39haa95532_0
  - superqt=0.7.6=py39hdfb3b6f_0
  - tbb=2021.8.0=h59b6b97_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=py39hbc747e5_1
  - threadpoolctl=3.5.0=py39h9909e9c_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.4.0=py39haa95532_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py39haa95532_0
  - tomlkit=0.13.2=py39haa95532_0
  - tornado=6.5.1=py39h827c3e9_0
  - tqdm=4.67.1=py39h9909e9c_0
  - traitlets=5.14.3=py39haa95532_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.10.0=py39h5da7b33_1
  - urllib3=2.5.0=py39haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py39haa95532_0
  - wcwidth=0.2.13=py39haa95532_0
  - webencodings=0.5.1=py39haa95532_1
  - whatthepatch=1.0.7=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - winloop=0.2.2=py39h913537a_0
  - wrapt=1.17.0=py39h827c3e9_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yapf=0.43.0=py39haa95532_0
  - yarl=1.18.0=py39h827c3e9_0
  - zeromq=4.3.5=h6c54ac7_1
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - cython==0.29.28
      - decorator==4.4.2
      - future==1.0.0
      - gensim==4.2.0
      - levenshtein==0.27.1
      - networkx==2.8.8
      - node2vec==0.4.5
      - pygsp==0.6.1
      - python-levenshtein==0.27.1
      - rapidfuzz==3.13.0
      - scipy==1.10.1
prefix: C:\Users\Megaport\anaconda3\envs\feature_generation
