name: ffstruc2vec-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.25
  - pip
  - pyarrow=21.0.0
  - tzdata
  - pip:
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - fastdtw==0.3.4
      - fonttools==4.60.1
      - future==1.0.0
      - gensim==4.3.1
      - hyperopt==0.2.7
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - matplotlib==3.6.3
      - networkx==2.8.8
      - numpy==1.23.5
      - packaging==25.0
      - pandas==1.5.3
      - pillow==11.3.0
      - py4j==0.10.9.9
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.1.3
      - scipy==1.10.1
      - six==1.17.0
      - smart-open==7.5.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - wrapt==2.0.1
      - xgboost==1.4.2