name: graphwave
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.9.25=h716150d_1
  - setuptools=80.9.0=py39haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alabaster==0.7.16
      - arrow==1.4.0
      - astroid==3.3.11
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - asyncssh==2.21.1
      - atomicwrites==1.4.1
      - attrs==25.4.0
      - autopep8==2.0.4
      - babel==2.17.0
      - backports-tarfile==1.2.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - binaryornot==0.4.4
      - black==25.9.0
      - bleach==6.2.0
      - cattrs==25.3.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - cookiecutter==2.6.0
      - cryptography==46.0.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diff-match-patch==20241021
      - dill==0.4.0
      - docstring-to-markdown==0.17
      - docutils==0.21.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - flake8==7.1.2
      - frozenlist==1.8.0
      - idna==3.11
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - inflection==0.5.1
      - intervaltree==3.1.0
      - ipykernel==6.31.0
      - ipython==8.18.1
      - ipython-pygments-lexers==1.1.1
      - isort==6.1.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jedi==0.19.2
      - jellyfish==1.2.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - keyring==25.6.0
      - lsprotocol==2025.0.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - more-itertools==10.8.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==2.0.2
      - numpydoc==1.9.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pydocstyle==6.3.0
      - pyflakes==3.2.0
      - pygithub==2.8.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylint==3.3.9
      - pylint-venv==3.0.4
      - pyls-spyder==0.4.0
      - pynacl==1.6.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.1
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.2
      - python-dateutil==2.9.0.post0
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-ruff==2.3.0
      - python-lsp-server==1.13.1
      - python-slugify==8.0.4
      - pytokens==0.2.0
      - pytoolconfig==1.3.1
      - pytz==2025.2
      - pyuca==1.2
      - pywin32==311
      - pywin32-ctypes==0.2.3
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qdarkstyle==3.2.3
      - qstylizer==0.2.4
      - qtawesome==1.4.0
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - referencing==0.36.2
      - requests==2.32.5
      - rich==14.2.0
      - rope==1.14.0
      - rpds-py==0.27.1
      - rtree==1.4.1
      - ruff==0.14.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sphinx==7.4.7
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - spyder==6.1.0
      - spyder-kernels==3.1.1
      - stack-data==0.6.3
      - superqt==0.7.6
      - text-unidecode==1.3
      - textdistance==4.6.3
      - threadpoolctl==3.6.0
      - three-merge==0.1.1
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tomlkit==0.13.3
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - whatthepatch==1.0.7
      - yapf==0.43.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\Megaport\anaconda3\envs\graphwave
